// <auto-generated />
namespace Altkom.Motorola.EF.DbServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddColorToDevice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColorToDevice));
        
        string IMigrationMetadata.Id
        {
            get { return "201808021126389_AddColorToDevice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
